/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/_index'
import { Route as IndexIndexImport } from './routes/_index/index'
import { Route as IndexReservationsImport } from './routes/_index/reservations'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/_index',
  getParentRoute: () => rootRoute,
} as any)

const IndexIndexRoute = IndexIndexImport.update({
  path: '/',
  getParentRoute: () => IndexRoute,
} as any)

const IndexReservationsRoute = IndexReservationsImport.update({
  path: '/reservations',
  getParentRoute: () => IndexRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_index': {
      id: '/_index'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_index/reservations': {
      id: '/_index/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof IndexReservationsImport
      parentRoute: typeof IndexImport
    }
    '/_index/': {
      id: '/_index/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexIndexImport
      parentRoute: typeof IndexImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute: IndexRoute.addChildren({
    IndexReservationsRoute,
    IndexIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_index"
      ]
    },
    "/_index": {
      "filePath": "_index.tsx",
      "children": [
        "/_index/reservations",
        "/_index/"
      ]
    },
    "/_index/reservations": {
      "filePath": "_index/reservations.tsx",
      "parent": "/_index"
    },
    "/_index/": {
      "filePath": "_index/index.tsx",
      "parent": "/_index"
    }
  }
}
ROUTE_MANIFEST_END */
